<a href="https://colab.research.google.com/github/cheauyuin/6m-data-1.7-intro-pandas/blob/main/1_7_Assignment_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 2: Practical Challenge (30–45 min)
**Scenario: "The Bookshop Analyst"**

You're a data analyst for an online bookshop. The operations team has exported their inventory to a CSV and they need your help making sense of it.

**Challenge 1: Build and Inspect the Dataset**

Create the following DataFrame and perform a health check:

In [2]:
import pandas as pd

books = pd.DataFrame({
    'title': ['The Pragmatic Programmer', 'Clean Code', 'Python Crash Course',
              'Data Science from Scratch', 'Designing Data-Intensive Apps'],
    'author': ['Hunt & Thomas', 'Robert Martin', 'Eric Matthes',
               'Joel Grus', 'Martin Kleppmann'],
    'genre': ['Tech', 'Tech', 'Tech', 'Data', 'Data'],
    'price': [45.99, 38.50, 29.99, 42.00, 55.00],
    'units_sold': [120, 95, 200, 80, 60],
    'in_stock': [True, True, False, True, False]
})

In [3]:
books

,title,author,genre,price,units_sold,in_stock
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True
1,Clean Code,Robert Martin,Tech,38.50,95,True
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False

1. Use `.info()` — how many non-null values does each column have?

In [4]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5 non-null      object
 1   author      5 non-null      object
 2   genre       5 non-null      object
 3   price       5 non-null      float64
 4   units_sold  5 non-null      int64
 5   in_stock    5 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 337.0+ bytes

2. Use `.describe()` — what's the average price and maximum units sold?

In [5]:
books.describe()

           price  units_sold
count   5.000000    5.000000
mean   42.296000  111.000000
std     9.232715   54.359912
min    29.990000   60.000000
25%    38.500000   80.000000
50%    42.000000   95.000000
75%    45.990000  120.000000
max    55.000000  200.000000

3. Add a `revenue` column: `price × units_sold`.

In [6]:
books['revenue'] = books['price'] * books['units_sold']
total_revenue = books['revenue'].sum()
print(total_revenue)

21834.3

In [7]:
books

,title,author,genre,price,units_sold,in_stock,revenue
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0

# Challenge 2: Indexing & Filtering

**Tasks:**

1. Use `.loc` to select only `title` and `revenue` for Data genre books.

In [8]:
data_books = books.loc[books['genre'] == 'Data', ['title', 'revenue']]
print(data_books)

                           title  revenue
3      Data Science from Scratch   3360.0
4  Designing Data-Intensive Apps   3300.0

2. Use `.iloc` to retrieve the last 3 rows and first 3 columns.

In [9]:
last3row_first3col = books.iloc[-3:, :3]
print(last3row_first3col)

                           title            author genre
2            Python Crash Course      Eric Matthes  Tech
3      Data Science from Scratch         Joel Grus  Data
4  Designing Data-Intensive Apps  Martin Kleppmann  Data

3. Filter books that are **in stock** AND have a **price above £40**.

In [10]:
instock_above40 = books[(books['in_stock'] == True) & (books['price'] > 40)]
print(instock_above40)

                       title         author genre  price  units_sold  \
0   The Pragmatic Programmer  Hunt & Thomas  Tech  45.99         120
3  Data Science from Scratch      Joel Grus  Data  42.00          80

   in_stock  revenue
0      True   5518.8
3      True   3360.0

4. Find the book with the **highest revenue** using `.loc` with `.idxmax()`.

In [11]:
highest_revenue_books = books.loc[books['revenue'].idxmax()]
print(highest_revenue_books)

title         Python Crash Course
author               Eric Matthes
genre                        Tech
price                       29.99
units_sold                    200
in_stock                    False
revenue                    5998.0
Name: 2, dtype: object

# Challenge 3: Transform, Sort & Rank
**Tasks:**

1. Use `.apply()` to add a `price_tier` column: `'Budget'` (< £35), `'Standard'` (£35–£50), `'Premium'` (> £50).

In [18]:
import pandas as pd

def get_price_tier(price):
    if price < 35:
        return 'Budget'
    elif 35 <= price <= 50:
        return 'Standard'
    else:
        return 'Premium'

books['price_tier'] = books['price'].apply(get_price_tier)
print(books)

                           title            author genre  price  units_sold  \
0       The Pragmatic Programmer     Hunt & Thomas  Tech  45.99         120
1                     Clean Code     Robert Martin  Tech  38.50          95
2            Python Crash Course      Eric Matthes  Tech  29.99         200
3      Data Science from Scratch         Joel Grus  Data  42.00          80
4  Designing Data-Intensive Apps  Martin Kleppmann  Data  55.00          60

   in_stock  revenue price_tier  sales_rank  genre_encoded
0      True   5518.8   Standard           2              0
1      True   3657.5   Standard           3              0
2     False   5998.0     Budget           1              0
3      True   3360.0   Standard           4              1
4     False   3300.0    Premium           5              1

2. Sort the DataFrame by `revenue` descending.

In [13]:
books_sorted_by_revenue = books.sort_values('revenue', ascending=False)
print(books_sorted_by_revenue)

                           title            author genre  price  units_sold  \
2            Python Crash Course      Eric Matthes  Tech  29.99         200
0       The Pragmatic Programmer     Hunt & Thomas  Tech  45.99         120
1                     Clean Code     Robert Martin  Tech  38.50          95
3      Data Science from Scratch         Joel Grus  Data  42.00          80
4  Designing Data-Intensive Apps  Martin Kleppmann  Data  55.00          60

   in_stock  revenue price_tier
2     False   5998.0     Budget
0      True   5518.8   Standard
1      True   3657.5   Standard
3      True   3360.0   Standard
4     False   3300.0    Premium

3. Add a `sales_rank` column using `.rank(ascending=False)`.

In [14]:
books['sales_rank'] = books['units_sold'].rank(ascending=False).astype(int)
print(books)

                           title            author genre  price  units_sold  \
0       The Pragmatic Programmer     Hunt & Thomas  Tech  45.99         120
1                     Clean Code     Robert Martin  Tech  38.50          95
2            Python Crash Course      Eric Matthes  Tech  29.99         200
3      Data Science from Scratch         Joel Grus  Data  42.00          80
4  Designing Data-Intensive Apps  Martin Kleppmann  Data  55.00          60

   in_stock  revenue price_tier  sales_rank
0      True   5518.8   Standard           2
1      True   3657.5   Standard           3
2     False   5998.0     Budget           1
3      True   3360.0   Standard           4
4     False   3300.0    Premium           5

4. Use `.map()` to encode `genre` as a number: `{'Tech': 0, 'Data': 1}`.

In [15]:
books['genre_encoded'] = books['genre'].map({'Tech': 0, 'Data': 1})
print(books)

                           title            author genre  price  units_sold  \
0       The Pragmatic Programmer     Hunt & Thomas  Tech  45.99         120
1                     Clean Code     Robert Martin  Tech  38.50          95
2            Python Crash Course      Eric Matthes  Tech  29.99         200
3      Data Science from Scratch         Joel Grus  Data  42.00          80
4  Designing Data-Intensive Apps  Martin Kleppmann  Data  55.00          60

   in_stock  revenue price_tier  sales_rank  genre_encoded
0      True   5518.8   Standard           2              0
1      True   3657.5   Standard           3              0
2     False   5998.0     Budget           1              0
3      True   3360.0   Standard           4              1
4     False   3300.0    Premium           5              1

# Stretch Challenge (Optional)
The manager wants a report comparing average price and total revenue by `price_tier`. Use `groupby()` to generate this summary. Which tier contributes the most total revenue despite having the lowest average price?

In [16]:
price_tier_summary = books.groupby('price_tier').agg(
    average_price=('price', 'mean'),
    total_revenue=('revenue', 'sum')
).reset_index().round(2)

print(price_tier_summary)

# Identify the tier with most total revenue and lowest average price
# First, find the tier with the lowest average price.
lowest_avg_price_tier = price_tier_summary.loc[price_tier_summary['average_price'].idxmin()]

print(f"\nTier with the lowest average price: {lowest_avg_price_tier['price_tier']}")
print(f"Total revenue for this tier: {lowest_avg_price_tier['total_revenue']}")

# Then, among all tiers, identify the one with the highest total revenue.
highest_revenue_tier = price_tier_summary.loc[price_tier_summary['total_revenue'].idxmax()]

print(f"\nTier with the highest total revenue: {highest_revenue_tier['price_tier']}")
print(f"Average price for this tier: {highest_revenue_tier['average_price']}")

  price_tier  average_price  total_revenue
0     Budget          29.99         5998.0
1    Premium          55.00         3300.0
2   Standard          42.16        12536.3

Tier with the lowest average price: Budget
Total revenue for this tier: 5998.0

Tier with the highest total revenue: Standard
Average price for this tier: 42.16

In [17]:
price_tier_summary = books.groupby('price_tier').agg(
    average_price=('price', 'mean'),
    total_revenue=('revenue', 'sum')
).reset_index().round(2)

print(price_tier_summary)

  price_tier  average_price  total_revenue
0     Budget          29.99         5998.0
1    Premium          55.00         3300.0
2   Standard          42.16        12536.3

The Standard tier contributed the most total revenue despite not being the highest average priced books. (lowest average priced book is the Budget tier, surprisingly, they are not the lowest revenue tier)

# Reflection
In 2–3 sentences, answer:
> Think of a dataset you might work with in your field. Which Pandas operation from today (indexing, .apply(), sorting, or ranking) would be most immediately useful? Why?

I find `.apply()` very useful in quickly comparing values and give labels / sort categorize rows into different groups.

Sorting and ranking works like a miracle. It is not possible to achieve simialr result with 1 simple sql statement.